config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      patch :up
      patch :down
    end
  end

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, -> { order "project_order ASC" }

  validates :name, presence: true

  def self.velocity_length_in_days
    21
  end

  def done?
    incomplete_tasks.empty?
  end

  def total_size
    tasks.to_a.sum(&:size)
  end

  def remaining_size
    incomplete_tasks.sum(&:size)
  end

  def incomplete_tasks
    tasks.reject(&:complete?)
  end

  def completed_velocity
    tasks.to_a.sum(&:points_toward_velocity)
  end

  def current_rate
    completed_velocity * 1.0 / Project.velocity_length_in_days
  end

  def projected_days_remaining
    remaining_size / current_rate
  end

  def on_schedule?
    projected_days_valid? && (Date.today + projected_days_remaining) <= due_date
  end

  def projected_days_valid?
    return !(projected_days_remaining.nan? || projected_days_remaining == Float::INFINITY)
  end

  def next_task_order
    return 1 if tasks.empty?
    (tasks.last.project_order || tasks.size) + 1
  end
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project

  def complete?
    completed_at.present?
  end

  def part_of_velocity?
    complete? && completed_at >= Project.velocity_length_in_days.days.ago
  end

  def first_in_project?
    return false unless project
    project.tasks.first == self
  end

  def last_in_project?
    return false unless project
    project.tasks.last == self
  end

  def my_place_in_tasks
    project.tasks.index(self)
  end

  def move_up
    swap_order_with(previous_task)
  end

  def move_down
    swap_order_with(next_task)
  end

  def swap_order_with(other)
    other.project_order, self.project_order = self.project_order, other.project_order
    other.save
    self.save
  end

  def next_task
    project.tasks[my_place_in_tasks + 1]
  end

  def previous_task
    project.tasks[my_place_in_tasks - 1]
  end

  def points_toward_velocity
    part_of_velocity? ? size : 0
  end

  def mark_completed(date = nil)
    self.completed_at = (date || Time.current)
  end

  def epic?
    size >= 5
  end

  def small?
    size <= 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @action = CreatesProject.new(name: params[:project][:name],
                                 task_string: params[:project][:tasks])
    success = @action.create
    if success
      redirect_to projects_path
    else
      @project = @action.project
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, notice: "project was successfully updated."
    else
      render action: 'edit'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def update
    @task = Task.find(params[:id])
    completed = params[:task].delete(:completed)
    params[:task][:completed_at] = Time.current if completed
    if @task.update_attributes(params[:task].permit(:size, :completed_at))
      TaskMailer.task_completed_email(@task).deliver if completed
      redirect_to @task, notice: "project was successfully updated."
    else
      render action: 'edit'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @project = Project.find(params[:task][:project_id])
    @project.tasks.create(title: params[:task][:title],
                          size: params[:task][:size],
                          project_order: @project.next_task_order)
    redirect_to @project
  end

  def up
    @task = Task.find(params[:id])
    @task.move_up
    redirect_to @task.project
  end

  def down
    @task = Task.find(params[:id])
    @task.move_down
    redirect_to @task.project
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def name_with_status(project)
    content_tag(:span, project.name,
                class: project.on_schedule? ? 'on_schedule' : 'behind_schedule')
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatherer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for @project do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :tasks %>
    <%= text_area_tag :"project[tasks]" %>
    <br>
    <%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<table>
  <thead>
  <tr>
    <td>Project Name</td>
    <td>Total Project Size</td>
  </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
      <tr class="project-row" id="<%= dom_id(project) %>">
        <td class="name"><%= name_with_status(project) %></td>
        <td class="total-size"><%= project.total_size %></td>
      </tr>

  <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for @project do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :tasks %>
    <%= text_area_tag :"project[tasks]" %>
    <br>
    <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h2>Project: <%= @project.name %></h2>
<h3>Existing Tasks:</h3>

<table>
  <thead>
  <tr>Name</tr>
  <tr>Size</tr>
  </thead>
  <tbody>
  <% @project.tasks.each do |task| %>
      <tr id="task_<%= task.project_order %>">
        <td class="name"><%= task.title %></td>
        <td class="size"><%= task.size %></td>
        <td class="completed"><%= task.completed_at.to_s %></td>
        <td>
          <% unless task.first_in_project? %>
            <%= link_to "Up", up_task_path(task.id), method: :patch %>
          <% end %>
          <% unless task.last_in_project? %>
            <%= link_to "Down", down_task_path(task.id), method: :patch %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<h3>New Task</h3>

<%= form_for Task.new(project_id: @project.id) do |f| %>
    <%= f.hidden_field :project_id %>
    <%= f.label :title, "Task" %>
    <%= f.text_field :title %>
    <%= f.label :size, "Size" %>
    <%= f.select :size, [1, 2, 3, 4, 5] %>
    <%= f.submit "Add Task" %>
<% end %>